name: Shell Executor Test
run-name: ${{ github.actor }} is testing shell execution
on:
    push:
        branches:
            - main
jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Run Script with parameters
              run: |
                ls
                chmod +x ./script.sh
                ./script.sh "para1" "param2"

    run-script-in-workflow:  
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Make script executable in the workflow
          run: chmod +x .github/workflows/script.sh

        - name: Execute shell script in the workflow dir
          run:  .github/workflows/script.sh "para1" "param2"



                

        