name: Shell Executor Test
run-name: ${{ github.actor }} is testing shell execution
on:
    push:
        branches:
            - main
jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Run Script with parameters
              run: |
                chmod +x ./script.sh
                ./script.sh "para1" "param2"

        